name: PandaEssentials
version: 0.0.1-SNAPSHOT
main: me.pandaplugins.pandaessentials.PandaEssentials
api-version: 1.13
authors: [TheCuddlyBear]
description: Plugin with essential commands like /kill
website: pjanda.nl
